-- MySQL Script generated by MySQL Workbench
-- Fri Nov  7 23:06:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sistemapagotarjeta
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistemapagotarjeta` ;

-- -----------------------------------------------------
-- Schema sistemapagotarjeta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemapagotarjeta` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Catalogo_Correo_Electronico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Catalogo_Correo_Electronico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Catalogo_Correo_Electronico` (
  `idCatalogo_Correo_Electronico` VARCHAR(50) NOT NULL,
  `Activo` BIT(1) NOT NULL,
  PRIMARY KEY (`idCatalogo_Correo_Electronico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Catalogo_Telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Catalogo_Telefono` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Catalogo_Telefono` (
  `idCatalogo_Telefono` INT NOT NULL,
  `Activo` BIT(1) NOT NULL,
  PRIMARY KEY (`idCatalogo_Telefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Correo_Electronico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Correo_Electronico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Correo_Electronico` (
  `idCorreo_Eelctronico` VARCHAR(50) NOT NULL,
  `Activo` BIT(1) NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `Catalogo_Correo_Electronico_idCatalogo_Correo_Electronico` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCorreo_Eelctronico`, `Persona_idPersona`),
  INDEX `fk_Correo_Eelctronico_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  INDEX `fk_Correo_Electronico_Catalogo_Correo_Electronico1_idx` (`Catalogo_Correo_Electronico_idCatalogo_Correo_Electronico` ASC) VISIBLE,
  CONSTRAINT `fk_Correo_Eelctronico_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `sistemapagotarjeta`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Correo_Electronico_Catalogo_Correo_Electronico1`
    FOREIGN KEY (`Catalogo_Correo_Electronico_idCatalogo_Correo_Electronico`)
    REFERENCES `mydb`.`Catalogo_Correo_Electronico` (`idCatalogo_Correo_Electronico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Telefono` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `idTelefono` INT NOT NULL,
  `Activo` BIT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `Catalogo_Telefono_idCatalogo_Telefono` INT NOT NULL,
  PRIMARY KEY (`idTelefono`, `Persona_idPersona`),
  INDEX `fk_Telefono_Persona_idx` (`Persona_idPersona` ASC) VISIBLE,
  INDEX `fk_Telefono_Catalogo_Telefono1_idx` (`Catalogo_Telefono_idCatalogo_Telefono` ASC) VISIBLE,
  CONSTRAINT `fk_Telefono_Persona`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `sistemapagotarjeta`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefono_Catalogo_Telefono1`
    FOREIGN KEY (`Catalogo_Telefono_idCatalogo_Telefono`)
    REFERENCES `mydb`.`Catalogo_Telefono` (`idCatalogo_Telefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_notificacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_notificacion` (
  `idtipo_notificacion` INT NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL,
  PRIMARY KEY (`idtipo_notificacion`))
ENGINE = InnoDB;

USE `sistemapagotarjeta` ;

-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`Persona` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Contrasenna` VARCHAR(255) NOT NULL,
  `Rol` INT NOT NULL,
  `Activo` BIT(1) NOT NULL,
  `Fecha_Creacion` DATETIME NOT NULL,
  `Fecha_Modificacion` DATETIME NOT NULL,
  `catalogo_genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `Correo` (`Correo` ASC) VISIBLE,
  INDEX `fk_Persona_catalogo_genero1_idx` (`catalogo_genero_idGenero` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_catalogo_genero1`
    FOREIGN KEY (`catalogo_genero_idGenero`)
    REFERENCES `sistemapagotarjeta`.`catalogo_genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Activo` BIT(1) NOT NULL DEFAULT b'1',
  `Fecha_Creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Fecha_Modificacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `catalogo_rol_usuario_idRol` INT NOT NULL,
  `Persona_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_catalogo_rol_usuario1_idx` (`catalogo_rol_usuario_idRol` ASC) VISIBLE,
  INDEX `fk_Usuario_Persona1_idx` (`Persona_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_catalogo_rol_usuario1`
    FOREIGN KEY (`catalogo_rol_usuario_idRol`)
    REFERENCES `sistemapagotarjeta`.`catalogo_rol_usuario` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`Persona_idUsuario`)
    REFERENCES `sistemapagotarjeta`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`autorizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`autorizacion` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`autorizacion` (
  `idAutorizacion` INT NOT NULL AUTO_INCREMENT,
  `idTransaccion` INT NOT NULL,
  `CodigoRespuesta` VARCHAR(10) NOT NULL,
  `Mensaje` VARCHAR(50) NOT NULL,
  `Aprobado` BIT(1) NOT NULL,
  `Fecha_Autorizacion` DATETIME NOT NULL,
  PRIMARY KEY (`idAutorizacion`),
  INDEX `idTransaccion` (`idTransaccion` ASC) VISIBLE,
  CONSTRAINT `autorizacion_ibfk_1`
    FOREIGN KEY (`idTransaccion`)
    REFERENCES `sistemapagotarjeta`.`transaccion` (`idTransaccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`bitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`bitacora` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`bitacora` (
  `idBitacora` INT NOT NULL AUTO_INCREMENT,
  `Modulo` VARCHAR(100) NOT NULL,
  `Accion` TEXT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `reporte_transaccion_idReporte` INT NOT NULL,
  `Usuario_idCliente` INT NOT NULL,
  PRIMARY KEY (`idBitacora`),
  INDEX `fk_bitacora_reporte_transaccion1_idx` (`reporte_transaccion_idReporte` ASC) VISIBLE,
  INDEX `fk_bitacora_Usuario1_idx` (`Usuario_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_bitacora_reporte_transaccion1`
    FOREIGN KEY (`reporte_transaccion_idReporte`)
    REFERENCES `sistemapagotarjeta`.`reporte_transaccion` (`idReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bitacora_Usuario1`
    FOREIGN KEY (`Usuario_idCliente`)
    REFERENCES `sistemapagotarjeta`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_emisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_emisor` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_emisor` (
  `idEmisor` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Emisor` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`idEmisor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_estado_transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_estado_transaccion` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_estado_transaccion` (
  `idEstadoTransaccion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`idEstadoTransaccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_genero` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_genero` (
  `idGenero` INT NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Activo` BIT(1) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_metodo_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_metodo_pago` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_metodo_pago` (
  `idMetodoPago` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`idMetodoPago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_rol_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_rol_usuario` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_rol_usuario` (
  `idRol` INT NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_tipo_cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_tipo_cuenta` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_tipo_cuenta` (
  `idTipoCuenta` INT NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL,
  PRIMARY KEY (`idTipoCuenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_tipo_moneda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_tipo_moneda` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_tipo_moneda` (
  `idTipoMoneda` INT NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Simbolo` VARCHAR(10) NOT NULL,
  `Activo` BIT(1) NOT NULL,
  PRIMARY KEY (`idTipoMoneda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_tipo_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_tipo_servicio` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_tipo_servicio` (
  `idTipoServicio` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`idTipoServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_tipo_sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_tipo_sucursal` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_tipo_sucursal` (
  `idTipoSucursal` INT NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL,
  PRIMARY KEY (`idTipoSucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_tipo_tarjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_tipo_tarjeta` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_tipo_tarjeta` (
  `idTipoTarjeta` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`idTipoTarjeta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`catalogo_tipo_transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`catalogo_tipo_transaccion` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`catalogo_tipo_transaccion` (
  `idTipoTransaccion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`idTipoTransaccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`cuenta` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`cuenta` (
  `NumeroCuenta` VARCHAR(100) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  `catalogo_tipo_cuenta_idTipoCuenta` INT NOT NULL,
  `Saldo` DECIMAL(10,2) NOT NULL,
  `catalogo_tipo_moneda_idTipoMoneda` INT NOT NULL,
  INDEX `Cliente_idCliente` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `Sucursal_idSucursal` (`Sucursal_idSucursal` ASC) VISIBLE,
  INDEX `fk_cuenta_catalogo_tipo_cuenta1_idx` (`catalogo_tipo_cuenta_idTipoCuenta` ASC) VISIBLE,
  INDEX `fk_cuenta_catalogo_tipo_moneda1_idx` (`catalogo_tipo_moneda_idTipoMoneda` ASC) VISIBLE,
  PRIMARY KEY (`NumeroCuenta`),
  CONSTRAINT `cuenta_ibfk_1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `sistemapagotarjeta`.`Usuario` (`idUsuario`),
  CONSTRAINT `cuenta_ibfk_2`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `sistemapagotarjeta`.`sucursal` (`idSucursal`),
  CONSTRAINT `fk_cuenta_catalogo_tipo_cuenta1`
    FOREIGN KEY (`catalogo_tipo_cuenta_idTipoCuenta`)
    REFERENCES `sistemapagotarjeta`.`catalogo_tipo_cuenta` (`idTipoCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_catalogo_tipo_moneda1`
    FOREIGN KEY (`catalogo_tipo_moneda_idTipoMoneda`)
    REFERENCES `sistemapagotarjeta`.`catalogo_tipo_moneda` (`idTipoMoneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`notificacion` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `Mensaje` VARCHAR(50) NOT NULL,
  `Medio` VARCHAR(50) NOT NULL,
  `EstadoEnvio` VARCHAR(50) NOT NULL,
  `FechaEnvio` DATETIME NOT NULL,
  `Usuario_idCliente` INT NOT NULL,
  `tipo_notificacion_idtipo_notificacion` INT NOT NULL,
  PRIMARY KEY (`idNotificacion`),
  INDEX `fk_notificacion_Usuario1_idx` (`Usuario_idCliente` ASC) VISIBLE,
  INDEX `fk_notificacion_tipo_notificacion1_idx` (`tipo_notificacion_idtipo_notificacion` ASC) VISIBLE,
  CONSTRAINT `fk_notificacion_Usuario1`
    FOREIGN KEY (`Usuario_idCliente`)
    REFERENCES `sistemapagotarjeta`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacion_tipo_notificacion1`
    FOREIGN KEY (`tipo_notificacion_idtipo_notificacion`)
    REFERENCES `mydb`.`tipo_notificacion` (`idtipo_notificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`pago` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `Metodo` INT NOT NULL,
  `Transaccion_idTransaccion` INT NOT NULL,
  `Monto` DECIMAL(10,2) NOT NULL,
  `catalogo_tipo_moneda_idTipoMoneda` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `Metodo` (`Metodo` ASC) VISIBLE,
  INDEX `Transaccion_idTransaccion` (`Transaccion_idTransaccion` ASC) VISIBLE,
  INDEX `fk_pago_catalogo_tipo_moneda1_idx` (`catalogo_tipo_moneda_idTipoMoneda` ASC) VISIBLE,
  CONSTRAINT `pago_ibfk_1`
    FOREIGN KEY (`Metodo`)
    REFERENCES `sistemapagotarjeta`.`catalogo_metodo_pago` (`idMetodoPago`),
  CONSTRAINT `pago_ibfk_2`
    FOREIGN KEY (`Transaccion_idTransaccion`)
    REFERENCES `sistemapagotarjeta`.`transaccion` (`idTransaccion`),
  CONSTRAINT `fk_pago_catalogo_tipo_moneda1`
    FOREIGN KEY (`catalogo_tipo_moneda_idTipoMoneda`)
    REFERENCES `sistemapagotarjeta`.`catalogo_tipo_moneda` (`idTipoMoneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`reporte_transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`reporte_transaccion` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`reporte_transaccion` (
  `idReporte` INT NOT NULL AUTO_INCREMENT,
  `Transaccion_idTransaccion` INT NOT NULL,
  `Fecha_Generado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Comentario` TEXT NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `Transaccion_idTransaccion` (`Transaccion_idTransaccion` ASC) VISIBLE,
  CONSTRAINT `reporte_transaccion_ibfk_1`
    FOREIGN KEY (`Transaccion_idTransaccion`)
    REFERENCES `sistemapagotarjeta`.`transaccion` (`idTransaccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`reverso_devolucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`reverso_devolucion` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`reverso_devolucion` (
  `idReverso` INT NOT NULL AUTO_INCREMENT,
  `idTransaccion` INT NOT NULL,
  `Motivo` VARCHAR(100) NOT NULL,
  `Fecha_Reverso` DATETIME NOT NULL,
  PRIMARY KEY (`idReverso`),
  INDEX `idTransaccion` (`idTransaccion` ASC) VISIBLE,
  CONSTRAINT `reverso_devolucion_ibfk_1`
    FOREIGN KEY (`idTransaccion`)
    REFERENCES `sistemapagotarjeta`.`transaccion` (`idTransaccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`servicio` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` TEXT NOT NULL,
  `idTipoServicio` INT NOT NULL,
  PRIMARY KEY (`idServicio`),
  INDEX `idTipoServicio` (`idTipoServicio` ASC) VISIBLE,
  CONSTRAINT `servicio_ibfk_1`
    FOREIGN KEY (`idTipoServicio`)
    REFERENCES `sistemapagotarjeta`.`catalogo_tipo_servicio` (`idTipoServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`sucursal` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(255) NOT NULL,
  `Activo` BIT(1) NOT NULL DEFAULT b'1',
  `Fecha_Creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Fecha_Modificacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `catalogo_tipo_sucursal_idTipoSucursal` INT NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_sucursal_catalogo_tipo_sucursal1_idx` (`catalogo_tipo_sucursal_idTipoSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_sucursal_catalogo_tipo_sucursal1`
    FOREIGN KEY (`catalogo_tipo_sucursal_idTipoSucursal`)
    REFERENCES `sistemapagotarjeta`.`catalogo_tipo_sucursal` (`idTipoSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`tarjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`tarjeta` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`tarjeta` (
  `idTarjeta` INT NOT NULL AUTO_INCREMENT,
  `Numero_Tarjeta` VARCHAR(20) NOT NULL,
  `Fecha_Expiracion` DATE NOT NULL,
  `idTipoTarjeta` INT NOT NULL,
  `idEmisor` INT NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  `Activo` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`idTarjeta`),
  INDEX `idTipoTarjeta` (`idTipoTarjeta` ASC) VISIBLE,
  INDEX `idEmisor` (`idEmisor` ASC) VISIBLE,
  CONSTRAINT `tarjeta_ibfk_1`
    FOREIGN KEY (`idTipoTarjeta`)
    REFERENCES `sistemapagotarjeta`.`catalogo_tipo_tarjeta` (`idTipoTarjeta`),
  CONSTRAINT `tarjeta_ibfk_2`
    FOREIGN KEY (`idEmisor`)
    REFERENCES `sistemapagotarjeta`.`catalogo_emisor` (`idEmisor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemapagotarjeta`.`transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistemapagotarjeta`.`transaccion` ;

CREATE TABLE IF NOT EXISTS `sistemapagotarjeta`.`transaccion` (
  `idTransaccion` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Estado` INT NOT NULL,
  `Tipo` INT NOT NULL,
  `idTarjeta` INT NOT NULL,
  `servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`idTransaccion`),
  INDEX `Estado` (`Estado` ASC) VISIBLE,
  INDEX `Tipo` (`Tipo` ASC) VISIBLE,
  INDEX `idTarjeta` (`idTarjeta` ASC) VISIBLE,
  INDEX `fk_transaccion_servicio1_idx` (`servicio_idServicio` ASC) VISIBLE,
  CONSTRAINT `transaccion_ibfk_1`
    FOREIGN KEY (`Estado`)
    REFERENCES `sistemapagotarjeta`.`catalogo_estado_transaccion` (`idEstadoTransaccion`),
  CONSTRAINT `transaccion_ibfk_2`
    FOREIGN KEY (`Tipo`)
    REFERENCES `sistemapagotarjeta`.`catalogo_tipo_transaccion` (`idTipoTransaccion`),
  CONSTRAINT `transaccion_ibfk_3`
    FOREIGN KEY (`idTarjeta`)
    REFERENCES `sistemapagotarjeta`.`tarjeta` (`idTarjeta`),
  CONSTRAINT `fk_transaccion_servicio1`
    FOREIGN KEY (`servicio_idServicio`)
    REFERENCES `sistemapagotarjeta`.`servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
